steps:
  # Build the ui image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ui', '-f', 'ui/Dockerfile', '.']
    waitFor: ['-']

  # Build the api-gateway image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway', '-f', 'api-gateway/Dockerfile', '.']
    waitFor: ['-']

  # Build the user-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-service', '-f', 'user-service/Dockerfile', '.']
    waitFor: ['-']

  # Build the matching-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/matching-service', '-f', 'matching-service/Dockerfile', '.']
    waitFor: ['-']

  # Build the question-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/question-service', '-f', 'question-service/Dockerfile', '.']
    waitFor: ['-']

  # Build the collaboration-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/collaboration-service', '-f', 'collaboration-service/Dockerfile', '.']
    waitFor: ['-']

  # Push all images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push gcr.io/$PROJECT_ID/ui
        docker push gcr.io/$PROJECT_ID/api-gateway
        docker push gcr.io/$PROJECT_ID/user-service
        docker push gcr.io/$PROJECT_ID/matching-service
        docker push gcr.io/$PROJECT_ID/question-service
        docker push gcr.io/$PROJECT_ID/collaboration-service

  # Deploy api-gateway to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'api-gateway', '--image', 'gcr.io/$PROJECT_ID/api-gateway', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

  # Deploy user-service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'user-service', '--image', 'gcr.io/$PROJECT_ID/user-service', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

  # Deploy matching-service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'matching-service', '--image', 'gcr.io/$PROJECT_ID/matching-service', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

  # Deploy question-service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'question-service', '--image', 'gcr.io/$PROJECT_ID/question-service', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

  # Deploy collaboration-service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'collaboration-service', '--image', 'gcr.io/$PROJECT_ID/collaboration-service', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

  # Deploy ui to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'ui', '--image', 'gcr.io/$PROJECT_ID/ui', '--region', 'asia-southeast1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/ui'
  - 'gcr.io/$PROJECT_ID/api-gateway'
  - 'gcr.io/$PROJECT_ID/user-service'
  - 'gcr.io/$PROJECT_ID/matching-service'
  - 'gcr.io/$PROJECT_ID/question-service'
  - 'gcr.io/$PROJECT_ID/collaboration-service'

options:
  logging: CLOUD_LOGGING_ONLY
