steps:
  # Build the ui image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ui', '-f', 'ui/Dockerfile', '.']
    waitFor: ['-']

  # Build the api-gateway image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway', '-f', 'api-gateway/Dockerfile', '.']
    waitFor: ['-']

  # Build the user-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-service', '-f', 'user-service/Dockerfile', '.']
    waitFor: ['-']

  # Build the matching-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/matching-service', '-f', 'matching-service/Dockerfile', '.']
    waitFor: ['-']

  # Build the question-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/question-service', '-f', 'question-service/Dockerfile', '.']
    waitFor: ['-']

  # Build the collaboration-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/collaboration-service', '-f', 'collaboration-service/Dockerfile', '.']
    waitFor: ['-']

images:
  - 'gcr.io/$PROJECT_ID/ui'
  - 'gcr.io/$PROJECT_ID/api-gateway'
  - 'gcr.io/$PROJECT_ID/user-service'
  - 'gcr.io/$PROJECT_ID/matching-service'
  - 'gcr.io/$PROJECT_ID/question-service'
  - 'gcr.io/$PROJECT_ID/collaboration-service'
