# connect with mongo atlas and redis cloud
name: algobuddy
services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
      args:
        NEXT_PUBLIC_USER_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_MATCHING_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_QUESTION_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_COLLABORATION_SERVICE_BASE_URL: ${API_GATEWAY_BASE_URL}
        NEXT_PUBLIC_PISTON_API_BASE_URL: ${PISTON_API_BASE_URL}
    image: ui:latest
    networks:
      - algobuddy
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:latest
    env_file:
      - ./.env.production
    ports:
      - "4000:4000"
    networks:
      - algobuddy
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service:latest
    hostname: "user-service"
    env_file:
      - ./.env.production
    networks:
      - algobuddy
  matching-service:
    build:
      context: .
      dockerfile: matching-service/Dockerfile
    image: matching-service:latest
    hostname: "matching-service"
    env_file:
      - ./.env.production
    networks:
      - algobuddy
  question-service:
    build:
      context: .
      dockerfile: question-service/Dockerfile
    image: question-service:latest
    hostname: "question-service"
    env_file:
      - ./.env.production
    networks:
      - algobuddy
  collaboration-service:
    build:
      context: .
      dockerfile: collaboration-service/Dockerfile
    image: collaboration-service:latest
    hostname: "collaboration-service"
    env_file:
      - ./.env.production
    networks:
      - algobuddy

networks:
  algobuddy:
